// <auto-generated />
namespace Orix.MeuControle.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AtualizacaoMappingAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtualizacaoMappingAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201701271520273_AtualizacaoMappingAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
